[package]
name = "leftshift"
version = "0.1.0"
authors = ["Ahtoms <me@ahtoms.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
rusqlite = "0.20"
chrono = "0.4"
